### ISSUE TITLE
Build error, different than that other guy I think.

### ISSUE THREAD

**Issue by imABitSpecial** [Bhaviktutorials/BloodyRat#4]
Here is the log.

```
ERROR | Build Failed - Build Command Failed - Command failed: java -jar "C:\RAT\BloodyRat-main\BloodyRat-main\server\app\factory\apktool.jar" b "C:\RAT\BloodyRat-main\BloodyRat-main\server\app\factory\decompiled" -o "C:\RAT\BloodyRat-main\BloodyRat-main\server\assets\webpublic\build.apk" Exception in thread "main" unacceptable code point '' (0x0) special characters are not allowed in "'reader'", position 0 at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:67) at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:248) at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:58) at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:499) at brut.androlib.meta.MetaInfo.load(MetaInfo.java:70) at brut.androlib.Androlib.readMetaFile(Androlib.java:262) at brut.androlib.Androlib.build(Androlib.java:276) at brut.androlib.Androlib.build(Androlib.java:269) at brut.apktool.Main.cmdBuild(Main.java:247) at brut.apktool.Main.main(Main.java:79)
```

**Comment by Bhaviktutorials** [comment]
provide me full screenshot of error

**Comment by imABitSpecial** [comment]
![image](https://user-images.githubusercontent.com/88986045/130361456-049cfb65-0629-4bfb-ae7b-ba7808657f79.png)

**Comment by Bhaviktutorials** [comment]
Did you install java?

**Comment by imABitSpecial** [comment]
Yes, JRE 7 or 8 I'm pretty sure

**Comment by imABitSpecial** [comment]
Tried again on Kali, which I've never used, and got this. How would I update it?
![image](https://user-images.githubusercontent.com/88986045/130370855-a531bda3-5ce5-41b3-b5e2-ae4667498707.png)

**Comment by Bhaviktutorials** [comment]
This error means u have install wrong version of java when ever free just contact me from whatsapp
https://wa.me/+919137810819
Will connect from TeamViewer and solve
